
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Haskell;

/** CUP generated class containing symbol constants. */
public class SimbolosHaskell {
  /* terminals */
  public static final int decc = 31;
  public static final int corCierra = 25;
  public static final int igualigual = 15;
  public static final int llaveAbre = 26;
  public static final int residuo = 6;
  public static final int mayorq = 11;
  public static final int par = 40;
  public static final int asc = 41;
  public static final int coma = 22;
  public static final int entonces = 45;
  public static final int igual = 17;
  public static final int llaveCierra = 27;
  public static final int calcular = 35;
  public static final int caracter = 51;
  public static final int let = 32;
  public static final int succ = 30;
  public static final int sum = 36;
  public static final int si = 44;
  public static final int puntoycoma = 23;
  public static final int corAbre = 24;
  public static final int max = 34;
  public static final int menos = 3;
  public static final int EOF = 0;
  public static final int mas = 2;
  public static final int revers = 38;
  public static final int menorq = 12;
  public static final int error = 1;
  public static final int entero = 49;
  public static final int or = 9;
  public static final int pot = 8;
  public static final int por = 4;
  public static final int indice = 20;
  public static final int mayorigualq = 13;
  public static final int dospuntos = 21;
  public static final int parenAbre = 28;
  public static final int parenCierra = 29;
  public static final int id = 52;
  public static final int concatena = 19;
  public static final int product = 37;
  public static final int sqrt = 7;
  public static final int caso = 47;
  public static final int impr = 39;
  public static final int fin = 48;
  public static final int tam = 43;
  public static final int menorigualq = 14;
  public static final int desc = 42;
  public static final int diferente = 16;
  public static final int and = 10;
  public static final int dolar = 18;
  public static final int div = 5;
  public static final int min = 33;
  public static final int cadena = 50;
  public static final int sino = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "residuo",
  "sqrt",
  "pot",
  "or",
  "and",
  "mayorq",
  "menorq",
  "mayorigualq",
  "menorigualq",
  "igualigual",
  "diferente",
  "igual",
  "dolar",
  "concatena",
  "indice",
  "dospuntos",
  "coma",
  "puntoycoma",
  "corAbre",
  "corCierra",
  "llaveAbre",
  "llaveCierra",
  "parenAbre",
  "parenCierra",
  "succ",
  "decc",
  "let",
  "min",
  "max",
  "calcular",
  "sum",
  "product",
  "revers",
  "impr",
  "par",
  "asc",
  "desc",
  "tam",
  "si",
  "entonces",
  "sino",
  "caso",
  "fin",
  "entero",
  "cadena",
  "caracter",
  "id"
  };
}

