
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Consola;

/** CUP generated class containing symbol constants. */
public class SimbolosConsola {
  /* terminals */
  public static final int decc = 20;
  public static final int corCierra = 16;
  public static final int residuo = 6;
  public static final int par = 29;
  public static final int asc = 30;
  public static final int coma = 13;
  public static final int igual = 9;
  public static final int calcular = 24;
  public static final int caracter = 35;
  public static final int let = 21;
  public static final int succ = 19;
  public static final int sum = 25;
  public static final int corAbre = 15;
  public static final int max = 23;
  public static final int menos = 3;
  public static final int porcentaje = 14;
  public static final int EOF = 0;
  public static final int mas = 2;
  public static final int revers = 27;
  public static final int error = 1;
  public static final int entero = 33;
  public static final int pot = 8;
  public static final int por = 4;
  public static final int indice = 12;
  public static final int parenAbre = 17;
  public static final int parenCierra = 18;
  public static final int id = 36;
  public static final int concatena = 11;
  public static final int sqrt = 7;
  public static final int product = 26;
  public static final int impr = 28;
  public static final int tam = 32;
  public static final int desc = 31;
  public static final int dolar = 10;
  public static final int div = 5;
  public static final int min = 22;
  public static final int cadena = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "residuo",
  "sqrt",
  "pot",
  "igual",
  "dolar",
  "concatena",
  "indice",
  "coma",
  "porcentaje",
  "corAbre",
  "corCierra",
  "parenAbre",
  "parenCierra",
  "succ",
  "decc",
  "let",
  "min",
  "max",
  "calcular",
  "sum",
  "product",
  "revers",
  "impr",
  "par",
  "asc",
  "desc",
  "tam",
  "entero",
  "cadena",
  "caracter",
  "id"
  };
}

