
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Graphik;

/** CUP generated class containing symbol constants. */
public class SimbolosGraphik {
  /* terminals */
  public static final int llaveCierra = 50;
  public static final int Tals = 8;
  public static final int menos = 54;
  public static final int carac = 43;
  public static final int graphikar = 21;
  public static final int punto = 72;
  public static final int parenAbre = 51;
  public static final int decremento = 69;
  public static final int importar = 12;
  public static final int fin = 74;
  public static final int div = 56;
  public static final int Tcadena = 5;
  public static final int parenCierra = 52;
  public static final int mas = 53;
  public static final int dospuntos = 71;
  public static final int mientras = 28;
  public static final int hereda = 13;
  public static final int imprimir = 37;
  public static final int llamar = 17;
  public static final int menorq = 63;
  public static final int privado = 10;
  public static final int sino = 24;
  public static final int procesar = 33;
  public static final int terminar = 31;
  public static final int caso = 25;
  public static final int mayorq = 62;
  public static final int menorigualq = 65;
  public static final int dondetodo = 36;
  public static final int or = 58;
  public static final int mayorigualq = 64;
  public static final int nuevo = 15;
  public static final int datos = 38;
  public static final int id = 40;
  public static final int dondecada = 35;
  public static final int Tdecimal = 3;
  public static final int seleccion = 23;
  public static final int protegido = 9;
  public static final int columna = 32;
  public static final int and = 59;
  public static final int retornar = 16;
  public static final int xor = 60;
  public static final int llamarHK = 19;
  public static final int cad = 39;
  public static final int corCierra = 48;
  public static final int Tvacio = 7;
  public static final int EOF = 0;
  public static final int inicio = 18;
  public static final int llaveAbre = 49;
  public static final int Tbool = 6;
  public static final int falso = 45;
  public static final int Tcaracter = 4;
  public static final int publico = 11;
  public static final int potencia = 57;
  public static final int verdadero = 44;
  public static final int nombreArchivo = 46;
  public static final int incluirHK = 20;
  public static final int corAbre = 47;
  public static final int error = 1;
  public static final int Tentero = 2;
  public static final int continuar = 30;
  public static final int diferente = 67;
  public static final int si = 22;
  public static final int hacer = 29;
  public static final int defecto = 26;
  public static final int igualigual = 66;
  public static final int donde = 34;
  public static final int por = 55;
  public static final int para = 27;
  public static final int coma = 73;
  public static final int not = 61;
  public static final int igual = 70;
  public static final int dec = 42;
  public static final int var = 14;
  public static final int incremento = 68;
  public static final int num = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tentero",
  "Tdecimal",
  "Tcaracter",
  "Tcadena",
  "Tbool",
  "Tvacio",
  "Tals",
  "protegido",
  "privado",
  "publico",
  "importar",
  "hereda",
  "var",
  "nuevo",
  "retornar",
  "llamar",
  "inicio",
  "llamarHK",
  "incluirHK",
  "graphikar",
  "si",
  "seleccion",
  "sino",
  "caso",
  "defecto",
  "para",
  "mientras",
  "hacer",
  "continuar",
  "terminar",
  "columna",
  "procesar",
  "donde",
  "dondecada",
  "dondetodo",
  "imprimir",
  "datos",
  "cad",
  "id",
  "num",
  "dec",
  "carac",
  "verdadero",
  "falso",
  "nombreArchivo",
  "corAbre",
  "corCierra",
  "llaveAbre",
  "llaveCierra",
  "parenAbre",
  "parenCierra",
  "mas",
  "menos",
  "por",
  "div",
  "potencia",
  "or",
  "and",
  "xor",
  "not",
  "mayorq",
  "menorq",
  "mayorigualq",
  "menorigualq",
  "igualigual",
  "diferente",
  "incremento",
  "decremento",
  "igual",
  "dospuntos",
  "punto",
  "coma",
  "fin"
  };
}

