
import java.io.BufferedReader;
import java.io.StringReader;
import Analizadores.Haskell.HaskellLexico;
import Analizadores.Haskell.HaskellSintactico;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxScheme;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMakerFactory;
import org.fife.ui.rtextarea.RTextScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MishaPks
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    
    ArrayList<pestaña> listaPestañas = new ArrayList();
    public static int nuevo;
    int contadorPestañas =0;
    public FormPrincipal() {
        initComponents();
       // configurarEditor();
    }

    private RSyntaxTextArea rsta;
    private void configurarEditor() {
        AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory) TokenMakerFactory.getDefaultInstance();
        atmf.putMapping("text/SBScript", "org.esvux.sbscript.ventanas.SBScriptSyntax");
        rsta = new RSyntaxTextArea(20, 60);
        rsta.setSyntaxEditingStyle("text/SBScript");
        rsta.setCodeFoldingEnabled(true);
        rsta.setCurrentLineHighlightColor(new Color(227, 242, 253, 200));
        rsta.setFadeCurrentLineHighlight(true);
        rsta.setBorder(BorderFactory.createEmptyBorder());
        rsta.addKeyListener(new java.awt.event.KeyAdapter() {
            
        });
        RTextScrollPane rtsp = new RTextScrollPane(rsta);
        rtsp.setViewportBorder(BorderFactory.createEmptyBorder());
        //jPanelPrincipal.add(rtsp);

        SyntaxScheme scheme = rsta.getSyntaxScheme();
        scheme.getStyle(Token.RESERVED_WORD).foreground = Color.decode("#0d47a1");
        scheme.getStyle(Token.LITERAL_STRING_DOUBLE_QUOTE).foreground = Color.decode("#e65100");
        scheme.getStyle(Token.IDENTIFIER).foreground = Color.decode("#1b5e20");
        scheme.getStyle(Token.DATA_TYPE).foreground = Color.decode("#42a5f5");
        scheme.getStyle(Token.COMMENT_EOL).foreground = Color.decode("#827717");
        scheme.getStyle(Token.COMMENT_MULTILINE).foreground = Color.decode("#827717");
        scheme.getStyle(Token.SEPARATOR).foreground = Color.black;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnNueva = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graphik y Haskell++");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 801, 455));

        btnNueva.setText("Nuevo Documento");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        new NuevoDocumento().setVisible(true);
        contadorPestañas++;
        if(NuevoDocumento.getHaskell()==1){ //haskell
            pestaña p = new pestaña();
            p.textPane = new JEditorPane();
            JScrollPane scrollPane = new JScrollPane(p.textPane);
            jTabbedPane1.add(scrollPane, "Archivo"+contadorPestañas+".hk");
            p.textPane.setContentType("text/java");
            listaPestañas.add(p);
            jTabbedPane1.setSelectedIndex(listaPestañas.size() - 1);
        } else if(NuevoDocumento.getGraphik() == 1){ //graphik
            pestaña p = new pestaña();
            p.textPane = new JEditorPane();
            JScrollPane scrollPane = new JScrollPane(p.textPane);
            jTabbedPane1.add(scrollPane, "Archivo"+contadorPestañas+".gk");
            p.textPane.setContentType("text/java");
            listaPestañas.add(p);
            jTabbedPane1.setSelectedIndex(listaPestañas.size() - 1);
        }
        
    }//GEN-LAST:event_btnNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNueva;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
