
import java.lang.reflect.Field;
import java.util.ArrayList;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MishaPks
 */
public class NuevoDocumento extends javax.swing.JFrame {

    static class ClaseConCampoEstatico {
        public static int nuevoHaskell=0;
        public static int nuevoGraphik=0;
    }

    
     ArrayList<pestaña> listaPestañas = new ArrayList();
    /**
     * Creates new form NuevoDocumento
     */
    public NuevoDocumento() {
        initComponents();
    }
    
    public static int getHaskell(){
        
        if(ClaseConCampoEstatico.nuevoHaskell==1){
            return 1;
        }else {
            return 0;
        }
    }
    public static int getGraphik(){
        if(ClaseConCampoEstatico.nuevoGraphik==1){
            return 1;
        }else{
            return 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHaskell = new javax.swing.JButton();
        btnGraphik = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(437, 194));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHaskell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Haskell.PNG"))); // NOI18N
        btnHaskell.setText("jButton1");
        btnHaskell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaskellActionPerformed(evt);
            }
        });
        getContentPane().add(btnHaskell, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 113));

        btnGraphik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Graphik.PNG"))); // NOI18N
        btnGraphik.setText("jButton1");
        btnGraphik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphikActionPerformed(evt);
            }
        });
        getContentPane().add(btnGraphik, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 150, 113));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 10, 150));

        jLabel1.setText("Haskell ++");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel2.setText("Graphik");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jPanel1.setMinimumSize(new java.awt.Dimension(402, 197));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHaskellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaskellActionPerformed
        cambiaValorHaskell(1);
       this.setVisible(false);
    }//GEN-LAST:event_btnHaskellActionPerformed

    private void btnGraphikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphikActionPerformed
        cambiaValorHaskell(1);
        this.setVisible(false);
    }//GEN-LAST:event_btnGraphikActionPerformed

    
    public static void cambiaValorHaskell(int nuevoValor) {
        try {
            Field field = ClaseConCampoEstatico.class.getDeclaredField("nuevoHaskell");
            field.setAccessible(true);
            field.setInt(null, nuevoValor);
        } catch (Exception e) {
            System.out.println("No se pudo cambiar el valor :(");
            e.printStackTrace(System.out);
        }
    }
    public static void cambiaValorGraphik(int nuevoValor) {
        try {
            Field field = ClaseConCampoEstatico.class.getDeclaredField("nuevoGraphik");
            field.setAccessible(true);
            field.setInt(null, nuevoValor);
        } catch (Exception e) {
            System.out.println("No se pudo cambiar el valor :(");
            e.printStackTrace(System.out);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraphik;
    private javax.swing.JButton btnHaskell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
