
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.lang.reflect.Field;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Utilities;
import org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxScheme;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMakerFactory;
import org.fife.ui.rtextarea.RTextScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MishaPks
 */
public class NuevoDocumento extends javax.swing.JFrame {

     public RSyntaxTextArea texto;
    /**
     * Creates new form NuevoDocumento
     */
    public NuevoDocumento() {
        initComponents();
    }
    
    
    private void Columna() {
        try {
            int caretPos = texto.getCaretPosition();
            int offset = Utilities.getRowStart(texto, caretPos);
            int colNum = caretPos - offset + 1;
            FormPrincipal.lblColumna.setText("   "+colNum);
        } catch (BadLocationException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHaskell = new javax.swing.JButton();
        btnGraphik = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setTitle("Nuevo Documento");
        setMinimumSize(new java.awt.Dimension(437, 194));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHaskell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Haskell.PNG"))); // NOI18N
        btnHaskell.setText("jButton1");
        btnHaskell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaskellActionPerformed(evt);
            }
        });
        getContentPane().add(btnHaskell, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 113));

        btnGraphik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Graphik.PNG"))); // NOI18N
        btnGraphik.setText("jButton1");
        btnGraphik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphikActionPerformed(evt);
            }
        });
        getContentPane().add(btnGraphik, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 150, 113));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 10, 150));

        jLabel1.setText("Haskell ++");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel2.setText("Graphik");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jPanel1.setMinimumSize(new java.awt.Dimension(402, 197));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTextEntradaKeyReleased(java.awt.event.KeyEvent evt) {
        
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
//ejecutar();
        }
    }
    
    private void btnHaskellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaskellActionPerformed
                
        //AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory) TokenMakerFactory.getDefaultInstance();
        //atmf.putMapping("text/FormPrincipal", "Analizadores.Haskell.HaskellLexico");
        texto = new RSyntaxTextArea(20, 60);
        texto.setCodeFoldingEnabled(true);
        texto.setCurrentLineHighlightColor(new Color(227, 242, 253, 200));
        texto.setFadeCurrentLineHighlight(true);
        texto.setName(".hk");
        texto.setBorder(BorderFactory.createEmptyBorder());
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Columna();
            }
        });
        RTextScrollPane pestaña = new RTextScrollPane(texto);
        pestaña.setName("ArchivoHaskell.hk");
        pestaña.setViewportBorder(BorderFactory.createEmptyBorder());
        FormPrincipal.jTabbedPane1.add(pestaña);
        FormPrincipal.listaPestañas.add(pestaña);
        this.setVisible(false);
        
      
    }//GEN-LAST:event_btnHaskellActionPerformed

    private void btnGraphikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphikActionPerformed
        
        texto = new RSyntaxTextArea(20, 60);
        texto.setCodeFoldingEnabled(true);
        texto.setCurrentLineHighlightColor(new Color(227, 242, 253, 200));
        texto.setFadeCurrentLineHighlight(true);
        texto.setName(".gk");
        texto.setBorder(BorderFactory.createEmptyBorder());
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Columna();
            }
        });
        RTextScrollPane pestaña = new RTextScrollPane(texto);
        pestaña.setName("ArchivoGraphik.gk");
        pestaña.setViewportBorder(BorderFactory.createEmptyBorder());
        FormPrincipal.jTabbedPane1.add(pestaña);
        FormPrincipal.listaPestañas.add(pestaña);
        this.setVisible(false);
    }//GEN-LAST:event_btnGraphikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraphik;
    private javax.swing.JButton btnHaskell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
